import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { createServer } from 'vite';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const appDir = path.resolve(scriptDir, '..');
const pharmacyDir = process.env.PHARMACY_SOURCE_DIR || path.resolve(scriptDir, '../../pharmacy');
const sourceCommit = execFileSync('git', ['-C', pharmacyDir, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();

async function loadModule(root, file) {
  const server = await createServer({
    root,
    configFile: false,
    server: { middlewareMode: true, hmr: false },
    appType: 'custom',
    resolve: { alias: { '@': root } },
  });
  try {
    return await server.ssrLoadModule(file);
  } finally {
    await server.close();
  }
}

const registry = await loadModule(pharmacyDir, '/data/clinicalRegistry.ts');
const seed = await loadModule(appDir, '/src/lib/pharmacySeedData.ts');

// The seed is generated from source IDs, so only map by these deterministic ID
// conventions. Do not use fuzzy titles for clinical entities.
const documentIds = new Set(seed.PHARMACY_SEED_DOCUMENTS.map((document) => document.id));
const slug = (value) => String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const documentIdFor = (entity) => {
  const sourceId = entity.sourceId || '';
  switch (entity.type) {
    case 'product':
      return `doc-product-${sourceId}`;
    case 'disease':
      return sourceId.startsWith('dis-')
        ? `doc-core-disease-${sourceId}`
        : `doc-disease-${sourceId.replace(/^otc-/, '')}`;
    case 'triage-scenario': {
      const category = sourceId.startsWith('admin-') ? 'admin' : sourceId.startsWith('slang-') ? 'slang' : 'clinical';
      return `doc-scenario-${category}-${sourceId}`;
    }
    case 'clinical-concept':
      return `doc-concept-${slug(sourceId)}`;
    case 'cyp-enzyme':
      return `doc-cyp-${sourceId.toLowerCase().replace(/[^a-z0-9]/g, '')}`;
    case 'mechanism':
      return `doc-mechanism-${slug(sourceId)}`;
    default:
      return undefined;
  }
};

const localTitleOverrides = {
  'triage:safescript-early-refill-s8': {
    fa: 'C4. هشدار SafeScript و درخواست جایگزینی زودهنگام داروی S8/S4 (NSW)',
    en: 'C4. SafeScript Alert & Early Replacement Request (NSW; S8/S4)',
  },
  'triage:admin-lost-escript-mysl': {
    fa: 'A1. توکن نسخهٔ الکترونیک گم‌شده: مسیر ASL/MySL و بازیابی',
    en: 'A1. Lost eScript Token: ASL/MySL Eligibility & Recovery',
  },
  'triage:thrush-triage': {
    fa: '۸. برفک واژینال در بارداری: تأیید تشخیص و انتخاب درمان',
    en: '8. Vaginal Thrush in Pregnancy: Confirm Diagnosis & Individualise Treatment',
  },
  'triage:chickenpox-advisory': {
    fa: '۵. آبله‌مرغان کودک: تسکین علائم و تفاوت راهنماهای ایبوپروفن',
    en: '5. Childhood Chickenpox: Symptom Relief & Conflicting Ibuprofen Advice',
  },
};

const entities = registry.CLINICAL_ENTITIES_UNIQUE.map((entity) => {
  const candidate = documentIdFor(entity);
  const documentId = candidate && documentIds.has(candidate) ? candidate : undefined;
  return {
    id: entity.id,
    type: entity.type,
    title: localTitleOverrides[entity.id] || entity.title,
    source: entity.source,
    sourceId: entity.sourceId,
    ...(entity.category ? { category: entity.category } : {}),
    ...(documentId ? { documentId } : {}),
  };
});
const entityIds = new Set(entities.map((entity) => entity.id));
const relations = registry.CLINICAL_RELATIONS.map((relation) => ({ ...relation }));

if (entityIds.size !== entities.length) throw new Error('Clinical entity IDs are not unique.');
if (new Set(relations.map((relation) => relation.id)).size !== relations.length) {
  throw new Error('Clinical relation IDs are not unique.');
}
const invalidRelations = relations.filter((relation) => !entityIds.has(relation.fromId) || !entityIds.has(relation.toId));
if (invalidRelations.length) throw new Error(`${invalidRelations.length} clinical relations reference missing entities.`);
const invalidDocumentIds = entities.filter((entity) => entity.documentId && !documentIds.has(entity.documentId));
if (invalidDocumentIds.length) throw new Error(`${invalidDocumentIds.length} clinical entities map to missing documents.`);
const mappedDocumentIds = entities.flatMap((entity) => entity.documentId ? [entity.documentId] : []);
if (new Set(mappedDocumentIds).size !== mappedDocumentIds.length) {
  throw new Error('More than one clinical entity maps to the same ARSHNAZ document.');
}

const body = [
  '/* Generated by scripts/generatePharmacyClinicalGraph.mjs; do not edit by hand. */',
  'export interface PharmacyClinicalEntity { id: string; type: string; title: { fa: string; en: string }; source: string; sourceId: string; category?: string; documentId?: string; }',
  'export interface PharmacyClinicalRelation { id: string; fromId: string; toId: string; type: string; confidence: "verified" | "suggested"; source: string; reason?: string; }',
  `export const PHARMACY_CLINICAL_SOURCE_COMMIT = ${JSON.stringify(sourceCommit)};`,
  `export const PHARMACY_CLINICAL_ENTITIES: readonly PharmacyClinicalEntity[] = ${JSON.stringify(entities, null, 2)};`,
  `export const PHARMACY_CLINICAL_RELATIONS: readonly PharmacyClinicalRelation[] = ${JSON.stringify(relations, null, 2)};`,
  '',
].join('\n');
const target = path.join(appDir, 'src/lib/pharmacyClinicalGraph.generated.ts');
fs.writeFileSync(target, body, 'utf8');

const mappedEntities = entities.filter((entity) => entity.documentId).length;
console.log(JSON.stringify({
  sourceCommit,
  entities: entities.length,
  mappedEntities,
  unmappedEntities: entities.length - mappedEntities,
  relations: relations.length,
  target,
}, null, 2));
